language: objective-c
osx_image: xcode7.3
xcode_project: SwiftValidation.xcodeproj
xcode_scheme: SwiftValidation
xcode_sdk: iphonesimulator9.3
after_success:
  - bash <(curl -s https://codecov.io/bash)
